Repository ucla-mobility/OpenCDA, pull requests merged in 2021-07, with the labels that each got.

#59 Feature/tutorial documentation
  .gitignore
  docs/PythonAPI.md
  docs/index.md
  opencda/co_simulation/__init__.py
  opencda/co_simulation/sumo_integration/bridge_helper.py
  opencda/co_simulation/sumo_integration/carla_simulation.py
  opencda/co_simulation/sumo_integration/sumo_simulation.py
  opencda/co_simulation/sumo_src/intersectionController.py
  opencda/co_simulation/sumo_src/simulationmanager.py
  opencda/co_simulation/sumo_src/vehicle.py
  opencda/core/actuation/control_manager.py
  opencda/core/actuation/pid_controller.py
  opencda/core/application/platooning/fsm.py
  opencda/core/application/platooning/platoon_behavior_agent.py
  opencda/core/application/platooning/platoon_debug_helper.py
  opencda/core/application/platooning/platooning_manager.py
  opencda/core/application/platooning/platooning_plugin.py
  opencda/core/common/cav_world.py
  opencda/core/common/misc.py
  opencda/core/common/v2x_manager.py
  opencda/core/common/vehicle_manager.py
  opencda/core/plan/behavior_agent.py
  opencda/core/plan/collision_check.py
  opencda/core/plan/drive_profile_plotting.py
  opencda/core/plan/global_route_planner.py
  opencda/core/plan/global_route_planner_dao.py
  opencda/core/plan/local_planner_behavior.py
  opencda/core/plan/planer_debug_helper.py
  opencda/core/plan/spline.py
  opencda/core/sensing/localization/coordinate_transform.py
  opencda/core/sensing/localization/kalman_filter.py
  opencda/core/sensing/localization/localization_debug_helper.py
  opencda/core/sensing/localization/localization_manager.py
  opencda/core/sensing/perception/o3d_lidar_libs.py
  opencda/core/sensing/perception/obstacle_vehicle.py
  opencda/core/sensing/perception/perception_manager.py
  opencda/core/sensing/perception/sensor_transformation.py
  opencda/customize/core/sensing/localization/extented_kalman_filter.py
  opencda/customize/core/sensing/localization/localization_manager.py
  opencda/customize/ml_libs/ml_manager.py
  opencda/opencda_carla.py
  opencda/scenario_testing/evaluations/evaluate_manager.py
  opencda/scenario_testing/evaluations/utils.py
  opencda/scenario_testing/utils/customized_map_api.py
  opencda/scenario_testing/utils/sim_api.py
  opencda/scenario_testing/utils/yaml_utils.py
Labels: documentation

#62 Feature/flake format
  README.md
  opencda/core/actuation/control_manager.py
  opencda/core/actuation/pid_controller.py
  opencda/core/application/platooning/fsm.py
  opencda/core/application/platooning/platoon_behavior_agent.py
  opencda/core/application/platooning/platoon_debug_helper.py
  opencda/core/application/platooning/platooning_manager.py
  opencda/core/application/platooning/platooning_plugin.py
  opencda/core/common/cav_world.py
  opencda/core/common/misc.py
  opencda/core/common/v2x_manager.py
  opencda/core/common/vehicle_manager.py
  opencda/core/plan/behavior_agent.py
  opencda/core/plan/collision_check.py
  opencda/core/plan/drive_profile_plotting.py
  opencda/core/plan/global_route_planner.py
  opencda/core/plan/global_route_planner_dao.py
  opencda/core/plan/local_planner_behavior.py
  opencda/core/plan/planer_debug_helper.py
  opencda/core/plan/spline.py
  opencda/core/sensing/localization/coordinate_transform.py
  opencda/core/sensing/localization/kalman_filter.py
  opencda/core/sensing/localization/localization_debug_helper.py
  opencda/core/sensing/localization/localization_manager.py
  opencda/core/sensing/perception/o3d_lidar_libs.py
  opencda/core/sensing/perception/obstacle_vehicle.py
  opencda/core/sensing/perception/perception_manager.py
  opencda/core/sensing/perception/sensor_transformation.py
  opencda/customize/core/sensing/localization/extented_kalman_filter.py
  opencda/customize/core/sensing/localization/localization_manager.py
  opencda/customize/ml_libs/ml_manager.py
  opencda/opencda_carla.py
  opencda/scenario_testing/evaluations/evaluate_manager.py
  opencda/scenario_testing/evaluations/utils.py
  opencda/scenario_testing/platoon_joining_2lanefree_carla.py
  opencda/scenario_testing/platoon_joining_2lanefreecomplete_carla.py
  opencda/scenario_testing/platoon_joining_town06_carla.py
  opencda/scenario_testing/platoon_stability_2lanefree_carla.py
  opencda/scenario_testing/single_2lanefree_carla.py
  opencda/scenario_testing/single_town06_carla.py
  opencda/scenario_testing/utils/customized_map_api.py
  opencda/scenario_testing/utils/sim_api.py
  opencda/scenario_testing/utils/yaml_utils.py
Labels: enhancement

#77 Feature/doc v01
  README.md
  docs/index.rst
  docs/md_files/contributor.md
  docs/md_files/getstarted.md
  docs/md_files/images/platoon_joining_cosim.gif
  docs/md_files/images/town06_cosim.gif
  docs/md_files/installation.md
  docs/md_files/introduction.md
  docs/md_files/logic_flow.md
  environment.yml
  opencda/scenario_testing/config_yaml/platoon_joining_2lanefree_cosim.yaml
  opencda/scenario_testing/platoon_joining_2lanefree_cosim.py
  requirements.txt
  setup.sh
Labels: documentation

#78 json file added
  opencda/co_simulation/sumo_integration/vtypes.json
Labels: bug

#80 Feature/planning refactor
  opencda/core/application/platooning/platoon_behavior_agent.py
  opencda/core/plan/behavior_agent.py
  opencda/core/plan/local_planner_behavior.py
  opencda/scenario_testing/config_yaml/single_intersection_town06_carla.yaml
Labels: documentation, enhancement

#81 add remove past waypoint function in buffer filter; add scenario_mana…
  opencda/core/plan/local_planner_behavior.py
  opencda/scenario_testing/config_yaml/single_intersection_town06_carla.yaml
  opencda/scenario_testing/cooperception_datadump_town06_carla.py
  opencda/scenario_testing/platoon_joining_2lanefree_carla.py
  opencda/scenario_testing/platoon_joining_2lanefreecomplete_carla.py
  opencda/scenario_testing/platoon_joining_town06_carla.py
  opencda/scenario_testing/platoon_stability_2lanefree_carla.py
  opencda/scenario_testing/single_2lanefree_carla.py
  opencda/scenario_testing/single_intersection_town06_carla.py
  opencda/scenario_testing/single_town06_carla.py
  opencda/scenario_testing/utils/sim_api.py
Labels: enhancement

#84 Documentation for v0.1.0
  README.md
  docs/index.rst
  docs/md_files/contributor.md
  docs/md_files/customization.md
  docs/md_files/getstarted.md
  docs/md_files/installation.md
  docs/md_files/introduction.md
  docs/md_files/logic_flow.md
  docs/md_files/traffic_generation.md
  docs/md_files/yaml_define.md
Labels: documentation

#100 Hotfix/intent fix
  opencda/scenario_testing/utils/sim_api.py
Labels: bug

#102 minor format issue fixed
  docs/index.rst
  docs/md_files/traffic_generation.md
Labels: documentation

#106 readme, intro and home page language modification
  README.md
  docs/index.rst
  docs/md_files/introduction.md
Labels: documentation

#108 Develop
  .travis.yml
  README.md
  docs/index.rst
  docs/md_files/introduction.md
  docs/md_files/traffic_generation.md
Labels: documentation
